const $=s=>document.querySelector(s);const app=$('#app');
const modules=[['home','Início'],['general','Evolução'],['has','Hipertensão'],['dm','Diabetes'],['both','HAS + DM'],['prenatal','Pré-natal'],['implante','Implanon'],['lab','Exames'],['rx','Receituário']];
const titles={implante:'Implanon · solicitação',prenatal:'Pré-natal',general:'Evolução geral',has:'Hipertensão',dm:'Diabetes',both:'Hipertensão + Diabetes',lab:'Exames laboratoriais',rx:'Receituário',history:'Histórico da sessão'};
let logged=false,page='home',drafts={},history=[],extraCount=0;
const generalState=['Bom estado geral','Regular estado geral','Sem alterações relevantes','Consciente','Orientado','Comunicativo','Deambulando','Restrito ao leito','Sem queixas no momento','Queixa principal'];
const evaluation=['Sem alterações','Estado geral preservado','Alimentação preservada','Hidratação preservada','Eliminações presentes','Sono preservado','Sem intercorrências','Refere queixas','Apresenta queixa'];
const generalActions=['Orientações realizadas','Medicação administrada','Medicação renovada','Exames solicitados','Encaminhamento realizado','Retorno orientado','Acompanhamento mantido','Adesão ao tratamento orientada','Orientação sobre alimentação','Orientação sobre atividade física','Orientação sobre uso correto das medicações','Orientação sobre sinais de alerta'];
const medsHas=['Medicamentos renovados','Uso regular das medicações orientado','Uso correto das medicações orientado','Adesão ao tratamento reforçada','Necessidade de avaliação médica sinalizada'];
const medsDm=['Medicamentos renovados','Uso correto das medicações orientado','Adesão ao tratamento reforçada','Tratamento mantido conforme prescrição','Necessidade de avaliação médica sinalizada'];
const guideHas=['Redução do consumo de sal','Alimentação saudável','Atividade física','Controle da pressão arterial','Acompanhamento regular','Sinais de alerta','Não interromper medicação sem orientação profissional'];
const guideDm=['Alimentação saudável','Controle glicêmico','Atividade física','Monitorização da glicemia','Uso correto das medicações','Cuidados com os pés','Inspeção dos pés','Hidratação da pele','Sinais de hipoglicemia','Sinais de hiperglicemia','Acompanhamento regular','Não interromper medicação sem orientação profissional'];
const examsHas=['Hemograma','Glicemia','HbA1c','Creatinina','Ureia','Perfil lipídico','Sódio','Potássio','TGO','TGP','EAS'];const examsDm=['Glicemia','HbA1c','Hemograma','Creatinina','Ureia','TFG/eTFG','Perfil lipídico','TGO','TGP','EAS'];
const returns=['Retorno orientado','Acompanhamento mantido','Reavaliação orientada','Encaminhamento realizado'];
const labs=[['Hemograma',['Hb','Ht','Leuco','Neutro','Linf','Mono','Eos','Baso','Plaq','VCM','HCM','CHCM','RDW']],['Glicemia',['Glic','HbA1c']],['Função renal',['Cr','Ur','TFG/eTFG']],['Função hepática',['TGO','TGP','GGT','FA','BT','BD','BI','Albumina']],['Perfil lipídico',['CT','HDL','LDL','TG','VLDL']],['Eletrólitos',['Na','K','Ca','Mg','Cl']],['Tireoide',['TSH','T4L','T3']]];
const percent=new Set(['Ht','Neutro','Linf','Mono','Eos','Baso','HbA1c','RDW']);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const unique=a=>[...new Set(a)];const join=a=>a.length<2?a.join(''):a.slice(0,-1).join(', ')+' e '+a.at(-1);const sentence=s=>s?s.charAt(0).toUpperCase()+s.slice(1).replace(/[.\s]+$/,'')+'.':'';
function toast(msg){const t=$('#toast');t.textContent=msg;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',3000)}
function login(){destroyReceituario();app.innerHTML=`<main class="login"><form class="login-card" id="login"><div class="logo"><span class="mark">+</span>EQUIPE 027</div><label>Login<input name="login" autocomplete="username" required autofocus></label><label>Senha<input name="password" type="password" autocomplete="current-password" required></label><p id="error" class="error" role="alert"></p><button class="primary">ENTRAR</button><small>Acesso de demonstração<br>Login: <b>equipe27</b> · Senha: <b>e27</b></small></form></main>`;$('#login').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('login')==='equipe27'&&f.get('password')==='e27'){logged=true;render()}else $('#error').textContent='Login ou senha incorretos.'}}
function collect(){const f=$('#clinical');if(!f)return;const d={};new FormData(f).forEach((v,k)=>{if(k.startsWith('c:')){(d[k]??=[]).push(v)}else d[k]=v});d.output=$('#output')?.value??'';d.stale=$('#output')?.dataset.stale==='true';drafts[page]=d}
function navigate(p){collect();page=p;render();window.scrollTo(0,0)}
function field(name,label,placeholder='',type='text'){return `<label>${label}<input name="${esc(name)}" type="${type}" ${type==='text'&&!['complaint','observations','otherActions','otherExams'].includes(name)?'inputmode="decimal"':''} placeholder="${esc(placeholder)}" autocomplete="off"></label>`}
function chips(key,values){return `<div class="chips">${values.map(v=>`<label class="chip"><input type="checkbox" name="c:${key}" value="${esc(v)}">${esc(['Medicamentos renovados','Medicação renovada'].includes(v)?'Avaliação médica solicitada e realizada; medicação renovada conforme orientação médica':v)}</label>`).join('')}</div>`}
function section(title,content){return `<section class="panel"><h2>${title}</h2>${content}</section>`}
function outputPanel(){return `<aside class="result"><button class="primary generate" id="generate">${page==='lab'?'GERAR LAB':'GERAR EVOLUÇÃO'}</button><section class="panel"><div class="row-title"><h2>${page==='lab'?'LAB gerado':'Evolução gerada'}</h2><span class="tag">Editável</span></div><label for="output" class="muted">Revise antes de copiar</label><textarea id="output" placeholder="O texto gerado aparecerá aqui. Apenas as informações preenchidas serão incluídas." spellcheck="true"></textarea><div class="actions"><button class="primary" id="copy">${page==='lab'?'COPIAR LAB':'COPIAR'}</button><button id="edit">Editar</button><button id="regenerate">Gerar novamente</button><button id="clear">Limpar</button></div></section><p class="privacy">Sem cadastro de pacientes. As informações ficam apenas nesta sessão e são apagadas ao sair ou recarregar a página.</p></aside>`}
function clinical(){const g=page==='general',has=page==='has'||page==='both',dm=page==='dm'||page==='both';let body=Notes.form(page);if(g)body+=section('Estado geral',chips('state',generalState)+`<div class="section-extra">${field('complaint','Queixa principal','Descreva, se houver')}</div>`);
let fs=g?[['pa','PA · mmHg','130/80'],['fc','FC · bpm'],['fr','FR · irpm'],['spo','SpO₂ · %'],['temp','T · °C'],['hgt','HGT · mg/dL'],['pain','Dor · /10']]:[...(has?[['pa','PA · mmHg','130/80'],['fc','FC · bpm']]:[]),...(dm?[['hgt','HGT · mg/dL'],['glic','Glicemia · mg/dL'],['a1c','HbA1c · %']]:[]),['weight','Peso · kg'],['bmi','IMC']];
body+=section(g?'Sinais vitais':'Avaliação rápida',`<div class="fields">${fs.map(x=>field(...x)).join('')}${g?'':`<label>Adesão ao tratamento<select name="adherence"><option value="">Não informado</option><option>Boa</option><option>Parcial</option><option>Baixa</option></select></label><div class="wide">${field('complaint','Queixas','Descreva, se houver')}</div>`}</div>`);
if(g){body+=section('Avaliação',chips('evaluation',evaluation)+`<label class="section-extra">Observações adicionais<textarea name="observations" rows="2"></textarea></label>`);body+=section('Condutas realizadas',chips('actions',generalActions))}else{body+=section('Medicamentos',chips('actions',unique([...(has?medsHas:[]),...(dm?medsDm:[])])));body+=section('Orientações',chips('guides',unique([...(has?guideHas:[]),...(dm?guideDm:[])])));body+=section('Exames solicitados',chips('examFlag',['Exames laboratoriais solicitados'])+`<div class="section-extra">${chips('exams',unique([...(has?examsHas:[]),...(dm?examsDm:[])]))}</div><div class="section-extra">${field('otherExams','Outros exames')}</div>`);body+=section('Retorno',chips('returns',returns))}
body+=`<details class="panel compact-details"><summary>Outras condutas (opcional)</summary><label>Outras condutas<textarea name="otherActions" rows="2" placeholder="Inclua somente condutas realizadas"></textarea></label></details>`;return `<div class="workspace"><form id="clinical" autocomplete="off">${body}</form>${outputPanel()}</div>`}
function labForm(){return `<div class="workspace"><form id="clinical" autocomplete="off">${section('Data da coleta',field('date','Data dos exames','','date'))}${labs.map(([name,ls])=>`<details class="lab-group" open><summary>${name}</summary><div class="fields">${ls.map(v=>field('lab:'+v,v+(percent.has(v)?' · %':''))).join('')}</div></details>`).join('')}${section('Outros exames',`<div id="extras"></div><button type="button" id="addLab">+ ADICIONAR EXAME</button>`)}</form>${outputPanel()}</div>`}
function addLab(values={}){const id=extraCount++;const row=document.createElement('div');row.className='lab-row';row.innerHTML=field('extraName:'+id,'Sigla/nome')+field('extraValue:'+id,'Valor')+field('extraUnit:'+id,'Unidade')+'<button type="button" aria-label="Remover exame">×</button>';row.querySelector('button').onclick=()=>row.remove();row.querySelectorAll('input').forEach((x,i)=>{x.removeAttribute('inputmode');x.value=[values.name,values.value,values.unit][i]??''});$('#extras').append(row)}
function dashboard(){const cards=[['general','✚','Evolução geral','Estado geral, avaliação e condutas.'],['has','♡','Hipertensão','Acompanhamento da pressão arterial.'],['dm','◇','Diabetes','Controle glicêmico e orientações.'],['both','⊕','Hipertensão + Diabetes','Uma evolução integrada, sem repetições.'],['prenatal','♡','Pré-natal','Idade gestacional, Protege, exame físico e condutas.'],['implante','✚','Implanon','Questionário e evolução para solicitação do implante.'],['lab','▤','Exames laboratoriais','Resultados no padrão LAB, prontos para copiar.'],['rx','℞','Receituário','Modelo de Lagarto/SE, impressão e exportação PNG.']];return `<div class="intro"><div class="eyebrow">Área de trabalho</div><h1 style="margin-top:12px">Qual registro vamos preparar?</h1><p class="muted">Selecione, preencha e copie para o sistema oficial.</p></div><div class="cards">${cards.map(([id,icon,t,d])=>`<button class="card" data-nav="${id}"><span class="icon">${icon}</span><span class="arrow">↗</span><strong>${t}</strong><p>${d}</p></button>`).join('')}</div><div class="bottom-note"><span>Informações temporárias · Nenhum cadastro de pacientes</span><button data-nav="history">Histórico da sessão (${history.length})</button></div>`}
function render(){if(!logged)return login();app.innerHTML=`<header class="top"><div class="logo"><span class="mark">+</span>EQUIPE 027</div><div class="session"><span>Ferramentas de enfermagem</span><button id="logout">Sair</button></div></header><nav aria-label="Navegação principal">${modules.map(([p,t])=>`<button data-nav="${p}" class="${page===p?'active':''}" ${page===p?'aria-current="page"':''}>${t}</button>`).join('')}</nav><main>${page==='home'?dashboard():`<div class="heading"><div><div class="eyebrow">EQUIPE 027 / ${page==='lab'?'Resultados':'Área de trabalho'}</div><h1 style="margin-top:10px">${titles[page]}</h1><p>${page==='rx'?'Preencha as duas vias, revise e imprima.':page==='history'?'Textos gerados nesta sessão.':'Preencha apenas o que foi avaliado ou realizado.'}</p></div><button data-nav="home">Início</button></div>`+(page==='rx'?`<p class="privacy rx-privacy">Os dados do receituário ficam apenas nesta sessão. Sair ou recarregar apaga o preenchimento.</p>`:page==='history'?historyView():page==='lab'?labForm():page==='prenatal'?Prenatal.form():page==='implante'?Implante.form():clinical())}</main>`;
syncReceituario();app.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));$('#logout').onclick=()=>{logged=false;drafts={};history=[];page='home';extraCount=0;login()};if($('#clinical')){restore();if(page==='prenatal')Prenatal.mount();if(page==='implante')Implante.mount();Notes.mount();enhanceWorkflow();$('#clinical').onsubmit=e=>e.preventDefault();$('#generate').onclick=generate;$('#regenerate').onclick=generate;$('#copy').onclick=()=>copy($('#output').value);$('#edit').onclick=()=>$('#output').focus();$('#clear').onclick=()=>{delete drafts[page];render();toast('Campos e texto limpos.')} ;if($('#addLab'))$('#addLab').onclick=()=>addLab();$('#clinical').addEventListener('change',resolveConflicts)}app.querySelectorAll('[data-copy-index]').forEach(b=>b.onclick=()=>copy(history[Number(b.dataset.copyIndex)].text));if($('#clearHistory'))$('#clearHistory').onclick=()=>{history=[];render()}}
function restore(){const d=drafts[page];if(!d)return;if(page==='lab'){Object.keys(d).filter(k=>k.startsWith('extraName:')).forEach(k=>{const id=k.split(':')[1];addLab({name:d[k],value:d['extraValue:'+id],unit:d['extraUnit:'+id]})})}$('#clinical').querySelectorAll('input,select,textarea').forEach(x=>{if(x.name.startsWith('extra'))return;if(x.type==='checkbox')x.checked=(d[x.name]??[]).includes(x.value);else x.value=d[x.name]??''});$('#output').value=d.output??'';$('#output').dataset.stale=d.stale?'true':'false'}
function resolveConflicts(e){const x=e.target;if(x.type!=='checkbox'||!x.checked)return;const groups=[['Bom estado geral','Regular estado geral'],['Deambulando','Restrito ao leito'],['Sem queixas no momento','Queixa principal','Refere queixas','Apresenta queixa']];for(const group of groups){if(group.includes(x.value)&&!(group.includes('Sem queixas no momento')&&x.value!=='Sem queixas no momento')){$('#clinical').querySelectorAll('input[type=checkbox]').forEach(y=>{if(y!==x&&group.includes(y.value))y.checked=false})}else if(group.includes('Sem queixas no momento')&&group.includes(x.value)){$('#clinical').querySelectorAll('input[type=checkbox]').forEach(y=>{if(y.value==='Sem queixas no momento')y.checked=false})}}}
function compose(d,p){if(p==='implante')return Implante.compose(d);if(p==='prenatal')return Prenatal.compose(d);const vals=k=>(d['c:'+k]??[]);const has=k=>String(d[k]??'').trim()!=='';const parts=[];if(p==='lab'){if(!has('date'))throw Error('Informe a data dos exames.');const date=d.date.split('-').reverse().join('/');const order=['Hb','Ht','Leuco','Neutro','Linf','Mono','Eos','Baso','Plaq','VCM','HCM','CHCM','RDW','Cr','Ur','TFG/eTFG','Glic','HbA1c','Na','K','Ca','Mg','Cl','TGO','TGP','GGT','FA','BT','BD','BI','Albumina','CT','HDL','LDL','TG','VLDL','TSH','T4L','T3'];const items=order.filter(k=>has('lab:'+k)).map(k=>k+' '+d['lab:'+k]+(percent.has(k)&&!d['lab:'+k].endsWith('%')?'%':''));Object.keys(d).filter(k=>k.startsWith('extraName:')).forEach(k=>{const id=k.split(':')[1],v='extraValue:'+id,u='extraUnit:'+id;if(has(k)!==has(v)||has(u)&&!has(k))throw Error('Complete o nome e o valor dos exames adicionais.');if(has(k)&&has(v))items.push(d[k]+' '+d[v]+(has(u)?' '+d[u]:''))});if(!items.length)throw Error('Preencha ao menos um resultado.');return `LAB (${date}): ${items.join(' | ')}.`}
return Notes.compose(d,p)}
function generate(){collect();try{const text=compose(drafts[page],page);$('#output').value=text;drafts[page].output=text;drafts[page].stale=false;markOutputFresh();saveHistory(text);toast(page==='lab'?'LAB gerado. Revise antes de copiar.':'Evolução gerada. Revise antes de copiar.')}catch(e){toast(e.message)}}
function saveHistory(text){if(!history.some(h=>h.text===text))history.unshift({text,type:titles[page]??'Texto',time:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})});}
async function copy(text){if(!text.trim())return toast('Gere um texto antes de copiar.');try{await navigator.clipboard.writeText(text);if(page!=='history')saveHistory(text);toast(page==='lab'?'LAB copiado!':'Evolução copiada!')}catch{toast('Não foi possível copiar automaticamente. Selecione e copie o texto.');$('#output')?.select()}}
function historyView(){return history.length?`<div class="row-title"><span class="muted">${history.length} texto(s) · apagados ao encerrar a sessão</span><button id="clearHistory">Limpar histórico</button></div>${history.map((h,i)=>`<article class="panel"><div class="row-title"><h2>${esc(h.type)}</h2><span class="tag">${h.time}</span></div><p class="history-text">${esc(h.text)}</p><button data-copy-index="${i}">Copiar</button></article>`).join('')}`:`<section class="panel empty"><h2>Nenhum texto nesta sessão</h2><p class="muted">As evoluções geradas aparecerão aqui temporariamente.</p><button class="primary" data-nav="general">Criar evolução</button></section>`}
window.addEventListener('pagehide',()=>{drafts={};history=[];logged=false;page='home';destroyReceituario();app.replaceChildren()});window.addEventListener('pageshow',e=>{if(e.persisted)login()});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'generate_current_nursing_note',description:'Gera o texto com os campos atualmente preenchidos na tela e o adiciona ao histórico temporário da sessão.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).length)throw Error('Nenhum parâmetro é aceito.');if(!logged||!$('#clinical'))throw Error('Abra um formulário após entrar.');collect();const text=compose(drafts[page],page);$('#output').value=text;drafts[page].output=text;drafts[page].stale=false;markOutputFresh();saveHistory(text);return{text}}})).catch(()=>{})}catch{}}
login();

// Keep one isolated document mounted across tab changes, only in memory.
function syncReceituario(){
  let host=document.getElementById('rx-host');
  document.body.classList.toggle('rx-open',logged&&page==='rx');
  if(logged&&page==='rx'&&!host){
    host=document.createElement('section');
    host.id='rx-host';
    host.setAttribute('aria-label','Preenchimento de receituário');
    const frame=document.createElement('iframe');
    frame.id='rx-frame';
    frame.title='Receituário da Secretaria Municipal da Saúde de Lagarto';
    frame.src='receituario.html';
    host.append(frame);
    app.after(host);
  }
  if(host)host.hidden=!logged||page!=='rx';
}
function destroyReceituario(){
  document.getElementById('rx-host')?.remove();
  document.body.classList.remove('rx-open');
}

// Reusable shortcuts without marking clinical findings automatically.
function enhanceWorkflow(){
  const form=$('#clinical');
  const nav=document.createElement('div');nav.className='form-shortcuts';nav.setAttribute('aria-label','Seções do formulário');
  [...form.children].forEach((el,i)=>{
    const title=el.querySelector('h2,summary');if(!title)return;
    el.id='form-section-'+i;
    const button=document.createElement('button');button.type='button';button.textContent=title.textContent;
    button.onclick=()=>{if(el.tagName==='DETAILS')el.open=true;el.scrollIntoView({behavior:'smooth',block:'start'})};nav.append(button);
  });
  form.before(nav);nav.style.gridColumn='1 / -1';
  const status=document.createElement('p');status.id='output-status';status.className='privacy';status.setAttribute('role','status');
  $('#output').after(status);
  const update=()=>{if($('#output').value.trim()){$('#output').dataset.stale='true';status.textContent='Campos alterados. Gere novamente para atualizar o texto.'}};
  form.addEventListener('input',update);form.addEventListener('change',update);
  if($('#output').dataset.stale==='true')status.textContent='Campos alterados. Gere novamente para atualizar o texto.';
  const quick=document.createElement('button');quick.className='primary mobile-generate';quick.textContent=page==='lab'?'Gerar LAB':'Gerar evolução';quick.type='button';quick.onclick=()=>{generate();$('.result').scrollIntoView({behavior:'smooth',block:'start'})};form.append(quick);
  form.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();generate()}});
}
function markOutputFresh(){
  if($('#output'))$('#output').dataset.stale='false';
  if($('#output-status'))$('#output-status').textContent='Texto atualizado. Revise antes de copiar.';
}
