/* Solicitação do implante: registro local, sem decisão automática de elegibilidade. */
const Implante=(()=>{
  const yesNo=['Sim','Não','Não sabe informar'];
  const triage=[['breast','Câncer de mama pessoal','câncer de mama pessoal'],['cervix','Câncer de colo do útero pessoal','câncer de colo do útero pessoal'],['liver','Doença hepática grave ou tumor hepático','doença hepática grave ou tumor hepático'],['thrombosis','Trombose / tromboembolismo','trombose ou tromboembolismo'],['bleeding','Sangramento genital sem causa esclarecida','sangramento genital sem causa esclarecida'],['allergy','Alergia ao etonogestrel ou componentes do implante','alergia ao etonogestrel ou componentes do implante']];
  const tests=[['hiv','HIV'],['syphilis','Sífilis'],['hb','Hepatite B (HBsAg)'],['hc','Hepatite C (anti-HCV)']];
  const guides={choice:'opções contraceptivas e escolha livre e informada',effect:'eficácia e duração do implante conforme orientação vigente',bleeding:'possíveis alterações do padrão de sangramento, inclusive amenorreia, sangramento irregular ou prolongado',effects:'possíveis efeitos adversos e necessidade de reavaliação se houver incômodo',removal:'possibilidade de retirada a pedido e retorno da fertilidade após remoção',sti:'ausência de proteção do implante contra IST e uso de preservativos',bridge:'contracepção até a inserção e eventual necessidade de proteção adicional conforme avaliação profissional',alerts:'sinais de alerta e quando procurar atendimento',process:'fluxo local da solicitação, inserção por profissional habilitado e acompanhamento'};
  const actions={assessment:'Realizada avaliação clínica para solicitação do implante',medical:'Solicitada avaliação médica',referral:'Realizado encaminhamento para avaliação por profissional habilitado',exams:'Solicitados exames conforme indicação clínica',counsel:'Realizado aconselhamento em planejamento reprodutivo',support:'Articulado apoio da equipe/rede de cuidado conforme necessidade identificada'};
  const v=(d,k)=>String(d[k]??'').trim();
  const choices=(d,k)=>Array.isArray(d['c:'+k])?d['c:'+k]:[];
  const fmt=x=>x.split('-').reverse().join('/');
  const finish=x=>x?x.replace(/[.\s]+$/,'')+'.':'';
  const input=(k,l,t='text',a='')=>`<label>${l}<input name="${k}" type="${t}" autocomplete="off" ${a}></label>`;
  const select=(k,l,opts)=>`<label>${l}<select name="${k}"><option value="">Não informado</option>${opts.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label>`;
  const area=(k,l)=>`<label class="section-extra">${l}<textarea name="${k}" rows="2"></textarea></label>`;
  const grid=x=>`<div class="fields two">${x}</div>`;
  const when=(k,vals,x)=>`<div class="section-extra" data-implant-if="${k}" data-values="${esc(vals.join('|'))}">${x}</div>`;
  const checks=(k,obj)=>`<div class="chips">${Object.entries(obj).map(([id,label])=>`<label class="chip"><input type="checkbox" name="c:${k}" value="${id}">${esc(label)}</label>`).join('')}</div>`;
  const number=(k,l,max=120)=>input(k,l,'number',`min="0" max="${max}" step="1"`);
  function form(){return `<div class="workspace"><form id="clinical" autocomplete="off">
    ${section('Solicitação do implante',`<p class="privacy">Questionário para avaliação e solicitação de implante de etonogestrel (Implanon). Não registra inserção nem aprova elegibilidade automaticamente. Campos em branco são omitidos.</p>${grid(input('visitDate','Data do atendimento','date')+number('age','Qual a idade?')+input('unit','Unidade / equipe')+select('requestReason','Qual o objetivo deste atendimento?',['Solicitação inicial','Atualização da solicitação','Reavaliação para solicitação']))}${area('motivation','Qual o motivo da escolha do implante / demanda atual?')}`)}
    ${section('História menstrual e obstétrica',`${grid(number('menarche','Menarca: com quantos anos?')+number('sexarche','Sexarca: com quantos anos?')+select('cycle','Como é o ciclo menstrual?',['Regular','Irregular','Amenorreia','Não sabe informar'])+input('dum','Data da última menstruação (DUM)','date')+number('interval','Intervalo habitual entre ciclos (dias)',365)+number('duration','Duração habitual do sangramento (dias)',90)+select('flow','Como é o fluxo menstrual?',['Habitual, sem alterações referidas','Reduzido','Aumentado','Variável','Não sabe informar'])+select('dysmenorrhea','Apresenta dismenorreia?',yesNo))}${area('menstrualNotes','Detalhes menstruais / motivo de DUM desconhecida')}${grid(number('g','Gestações (G)',40)+number('p','Partos (P)',40)+number('a','Abortamentos (A)',40)+select('delivery','Quais foram as vias de parto?',['Vaginal','Cesárea','Vaginal e cesárea'])+select('riskPregnancy','Houve gestação de risco?',yesNo)+select('obstetricComplications','Houve intercorrências gestacionais ou obstétricas?',yesNo))}${area('obstetricNotes','Detalhes obstétricos, abortamentos e intercorrências')}${grid(select('postpartum','Está no pós-parto ou pós-abortamento?',['Não','Pós-parto','Pós-abortamento'])+select('breastfeeding','Está amamentando?',['Não','Sim, exclusivamente ou quase exclusivamente','Sim, parcialmente']))}${when('postpartum',['Pós-parto','Pós-abortamento'],input('eventDate','Data do parto / abortamento','date'))}`)}
    ${section('Vida sexual e contracepção',`${grid(select('sexualActivity','Atividade sexual atual?',['Ativa','Inativa','Prefere não informar'])+select('partners','Parcerias sexuais (se pertinente)?',['Parceria única','Múltiplas parcerias','Sem parceria atual','Prefere não informar'])+select('contraception','Usa método contraceptivo atualmente?',yesNo)+select('condom','Uso de preservativos?',['Sempre','Às vezes','Nunca','Não se aplica']))}${when('contraception',['Sim'],grid(input('method','Qual método / nome do anticoncepcional?')+input('methodTime','Há quanto tempo usa?')+select('regularUse','Utiliza de forma regular e correta?',yesNo)+input('lastDose','Última dose / aplicação (se pertinente)','date'))+area('methodNotes','Esquecimentos, atrasos, falhas ou efeitos indesejados'))}${area('previousMethods','Métodos anteriores / motivo da troca')}${grid(select('unprotected','Relação sem proteção ou falha contraceptiva recente?',yesNo)+select('pregnancySymptoms','Atraso menstrual ou sintomas sugestivos de gestação?',yesNo))}${when('unprotected',['Sim'],input('unprotectedDate','Data da relação / falha mais recente','date'))}${area('pregnancyBasis','Informações para avaliação de possibilidade de gestação')}${grid(select('pregnancyAssessment','Conclusão registrada pelo profissional sobre gestação',['Avaliação pendente','Não foi possível afastar gestação','Razoável certeza de ausência de gestação','Gestação confirmada'])+select('pregnancyTest','Teste de gravidez',['Não realizado','Solicitado','Aguardando resultado','Negativo','Positivo','Inconclusivo']))}${when('pregnancyTest',['Negativo','Positivo','Inconclusivo'],grid(input('pregnancyTestDate','Data do teste de gravidez','date')+input('pregnancyTestType','Tipo de teste / resultado quantitativo')))}<p class="privacy">Teste negativo isolado não exclui gestação muito recente. Registre a avaliação profissional e sua fundamentação; o sistema não interpreta o teste.</p>`)}
    ${section('Antecedentes e medicamentos',`${grid(triage.map(([k,l])=>select(k,l+'?', ['Nega','Refere atual','Refere antecedente','Não sabe informar'])).join(''))}${area('healthDetails','Detalhes: diagnóstico, época, tratamento e situação atual')}${area('familyHistory','Histórico familiar relevante (separado do histórico pessoal)')}${area('otherConditions','Outras condições clínicas / cirurgias / alergias')}${grid(select('meds','Está em uso de medicamentos ou fitoterápicos?',yesNo)+select('interactions','Interações medicamentosas foram revisadas?',['Ainda não avaliadas','Revisadas; sem interação identificada pelo profissional','Possível interação; requer avaliação']))}${when('meds',['Sim'],area('medList','Quais medicamentos, fitoterápicos e doses em uso?'))}${area('interactionNotes','Detalhes da revisão de interações / encaminhamento') }<p class="privacy">Distinguir doença atual, antecedente pessoal e familiar. Registrar possíveis interações, especialmente com indutores enzimáticos, para avaliação profissional. Nenhuma resposta isolada gera autorização ou recusa do método.</p>`)}
    ${section('IST, rastreamento e exame físico',`${grid(select('stiHistory','Histórico de IST?',['Nega','Refere','Não sabe informar'])+input('cytologyDate','Data do último citopatológico','date'))}${when('stiHistory',['Refere'],area('stiDetails','Qual IST, tratamento e seguimento?'))}${grid(select('cytologyStatus','Situação do citopatológico',['Nunca realizado','Não sabe informar','Realizado; resultado indisponível','Resultado disponível','Coleta solicitada'])+input('cytologyResult','Resultado / seguimento, conforme laudo'))}<p class="privacy">Registre rastreamento e testes quando disponíveis. Citopatológico e testes de IST não são exigidos por este formulário para gerar a solicitação.</p>${tests.map(([k,l])=>`<div class="section-extra">${grid(select(k,'Teste rápido: '+l,['Não realizado','Recusado','Solicitado','Aguardando resultado','Não reagente','Reagente','Inválido / inconclusivo'])+input(k+'Date','Data do teste: '+l,'date'))}</div>`).join('')}${area('testNotes','Observações dos testes / condutas diante dos resultados')}${grid(input('pa','PA (mmHg)')+input('weight','Peso (kg)','number','min="0" step="0.1"'))}${area('physical','Exame físico realizado: achados relevantes')}`)}
    ${section('Orientações e decisão compartilhada',`<p class="privacy">Marque somente as orientações efetivamente realizadas.</p>${checks('implantGuides',guides)}${grid(select('decision','Qual a decisão expressa pela paciente?',['Deseja o implante após aconselhamento','Deseja mais tempo para decidir','Prefere outro método','Não deseja prosseguir no momento'])+select('understanding','Compreensão das informações',['Compreensão confirmada pelo profissional','Persistem dúvidas; necessita novo esclarecimento']))}${area('questions','Dúvidas, preferências e outras orientações')}`)}
    ${section('Conduta e cadastro da solicitação',`${checks('implantActions',actions)}${area('assessment','Avaliação profissional e justificativa da conduta')}${grid(select('consent','Situação do termo de consentimento',['Não abordado','Orientado / entregue para leitura','Preenchido; assinatura pendente','Lido, esclarecido e assinado','Paciente não consentiu neste momento'])+select('scoreStatus','Avaliação / escore de vulnerabilidade',['Não realizado','Pendente','Realizado conforme protocolo local','Não se aplica ao fluxo local']))}${when('scoreStatus',['Realizado conforme protocolo local'],grid(input('scoreProtocol','Nome e versão do instrumento / protocolo')+input('scoreValue','Pontuação obtida (transcrição)'))+area('scoreNotes','Resultado / necessidades de apoio identificadas'))}<p class="privacy">Transcreva o instrumento adotado pelo serviço. Não há cálculo automático, ponto de corte ou priorização presumida.</p>${grid(select('requestStatus','Situação da solicitação',['Cadastro preenchido; ainda não enviado','Solicitação enviada / inserida na regulação','Aguardando avaliação profissional','Aguardando agendamento','Inserção agendada','Solicitação adiada para investigação','Paciente optou por não prosseguir'])+input('reference','Número do protocolo / serviço de referência'))}${area('bridgePlan','Método / orientação contraceptiva até a avaliação ou inserção')}${grid(select('renewal','Houve renovação de medicamento?',['Não','Avaliação médica solicitada; aguardando definição','Avaliação médica solicitada e realizada; renovação conforme orientação médica']))}${when('renewal',['Avaliação médica solicitada e realizada; renovação conforme orientação médica'],area('renewedMeds','Quais medicamentos foram renovados?'))}${area('conduct','Outras condutas realizadas / exames solicitados / encaminhamentos')}${grid(input('returnDate','Data do retorno / agendamento','date')+input('returnPlace','Finalidade, horário e local do retorno'))}${grid(input('contact','Contato informado pela paciente (opcional)','tel')+input('contactPreference','Canal e horário seguros para contato (opcional)'))}${area('professional','Profissional responsável / registro (opcional)')}`)}
    <details class="panel compact-details"><summary>Referências e limites do questionário</summary><p>Registro de avaliação e solicitação, sem atestar inserção. Confirmar elegibilidade, interações e fluxo com profissional habilitado e protocolo local vigente.</p><p><a href="https://esppe.saude.pe.gov.br/pluginfile.php/279052/mod_folder/content/0/Manual%20para%20inser%C3%A7%C3%A3o%20do%20implante%20subd%C3%A9rmico.pdf?forcedownload=1" target="_blank" rel="noopener">Ministério da Saúde: manual de inserção, versão preliminar (2025)</a></p><p><a href="https://www.gov.br/saude/pt-br/centrais-de-conteudo/publicacoes/notas-tecnicas/2025/nota-tecnica-no-419-2025-dgci-desco-saps-ms.pdf/view" target="_blank" rel="noopener">Nota Técnica Conjunta 419/2025 — Ministério da Saúde</a></p><p>Revisão das referências: 23/09/2026. O protocolo e o escore específico de Lagarto não foram verificados; informar o instrumento do serviço.</p></details>
    </form>${outputPanel()}</div>`;}
  function mount(){const form=document.getElementById('clinical');const refresh=()=>{form.querySelectorAll('[data-implant-if]').forEach(el=>{const show=el.dataset.values.split('|').includes(form.elements[el.dataset.implantIf].value);el.hidden=!show;el.querySelectorAll('input,textarea,select').forEach(x=>x.disabled=!show)});};form.addEventListener('change',refresh);refresh();}
  function validate(d){
    const ranges={age:120,menarche:120,sexarche:120,interval:365,duration:90,g:40,p:40,a:40};
    for(const [k,max] of Object.entries(ranges))if(v(d,k)&&(!/^\d+$/.test(v(d,k))||+d[k]>max))throw Error('Confira os valores numéricos do questionário.');
    for(const k of ['menarche','sexarche'])if(v(d,k)&&v(d,'age')&&+d[k]>+d.age)throw Error('Menarca e sexarca não podem ser posteriores à idade informada.');
    if(v(d,'g')&&v(d,'p')&&+d.p>+d.g||v(d,'g')&&v(d,'a')&&+d.a>+d.g||['g','p','a'].every(k=>v(d,k))&&+d.p+(+d.a)>+d.g)throw Error('Confira G/P/A: partos e abortamentos não podem exceder as gestações.');
    for(const k of ['visitDate','dum','lastDose','eventDate','unprotectedDate','pregnancyTestDate','cytologyDate','returnDate',...tests.map(([k])=>k+'Date')]){
      if(!v(d,k))continue;const n=Date.parse(d[k]+'T00:00:00Z');if(!/^\d{4}-\d{2}-\d{2}$/.test(d[k])||!Number.isFinite(n)||new Date(n).toISOString().slice(0,10)!==d[k])throw Error('Confira as datas preenchidas.');
      if(v(d,'visitDate')&&k!=='returnDate'&&d[k]>d.visitDate)throw Error('Datas de antecedentes e exames não podem ser posteriores ao atendimento.');
    }
    if(v(d,'returnDate')&&v(d,'visitDate')&&d.returnDate<d.visitDate)throw Error('O retorno não pode ser anterior ao atendimento.');
    if(d.pregnancyTest==='Positivo'&&d.pregnancyAssessment==='Razoável certeza de ausência de gestação')throw Error('Revise a conclusão sobre gestação: foi informado teste positivo.');
    if(d.pregnancyAssessment==='Razoável certeza de ausência de gestação'&&!v(d,'pregnancyBasis'))throw Error('Registre a fundamentação da avaliação de ausência de gestação.');
    if(d.scoreStatus==='Realizado conforme protocolo local'&&v(d,'scoreValue')&&!v(d,'scoreProtocol'))throw Error('Informe o instrumento / protocolo associado à pontuação de vulnerabilidade.');
    if(d.requestStatus==='Inserção agendada'&&!v(d,'returnDate'))throw Error('Informe a data da inserção agendada.');
    if(['Paciente não consentiu neste momento'].includes(d.consent)&&d.requestStatus==='Inserção agendada'||['Não deseja prosseguir no momento','Prefere outro método'].includes(d.decision)&&d.requestStatus==='Inserção agendada')throw Error('Revise o agendamento e a decisão / consentimento registrados.');
  }
  function compose(d){validate(d);const groups=[];const push=a=>{if(a.length)groups.push(a.map(finish).join(' '))};const item=(a,k,label)=>{if(v(d,k))a.push(label+': '+v(d,k))};const date=(a,k,label)=>{if(v(d,k))a.push(label+': '+fmt(d[k]))};const yn=(a,k,yes,no,unknown)=>{if(d[k]==='Sim')a.push(yes);else if(d[k]==='Não')a.push(no);else if(d[k]==='Não sabe informar')a.push(unknown)};
    const intro=['Paciente'+(v(d,'age')?', '+d.age+' anos,':'')+' comparece à unidade para avaliação e solicitação de implante contraceptivo subdérmico de etonogestrel (Implanon)'];date(intro,'visitDate','Atendimento');item(intro,'unit','Unidade/equipe');item(intro,'requestReason','Finalidade');item(intro,'motivation','Demanda e motivo da escolha');push(intro);
    const m=[];if(v(d,'menarche'))m.push('Refere menarca aos '+d.menarche+' anos');if(v(d,'sexarche'))m.push('Refere sexarca aos '+d.sexarche+' anos');item(m,'cycle','Padrão menstrual referido');date(m,'dum','DUM');if(v(d,'interval'))m.push('Intervalo menstrual habitual de '+d.interval+' dias');if(v(d,'duration'))m.push('Duração habitual do sangramento de '+d.duration+' dias');item(m,'flow','Fluxo');yn(m,'dysmenorrhea','Refere dismenorreia','Nega dismenorreia','Não sabe informar sobre dismenorreia');item(m,'menstrualNotes','Observações menstruais');push(m);
    const o=[];const gpa=['g','p','a'].filter(k=>v(d,k)).map(k=>k.toUpperCase()+d[k]);if(gpa.length)o.push('Histórico obstétrico referido: '+gpa.join(' '));item(o,'delivery','Via(s) de parto referida(s)');yn(o,'riskPregnancy','Refere gestação de risco prévia','Nega gestação de risco prévia','Não sabe informar sobre gestação de risco prévia');yn(o,'obstetricComplications','Refere intercorrências gestacionais/obstétricas','Nega intercorrências gestacionais/obstétricas','Não sabe informar sobre intercorrências obstétricas');item(o,'obstetricNotes','Detalhes obstétricos');if(d.postpartum==='Não')o.push('Nega estar em período pós-parto ou pós-abortamento');else if(v(d,'postpartum')){item(o,'postpartum','Situação atual');date(o,'eventDate','Data do evento obstétrico');}item(o,'breastfeeding','Amamentação');push(o);
    const s=[];item(s,'sexualActivity','Atividade sexual atual');item(s,'partners','Parcerias referidas');item(s,'condom','Uso de preservativos');yn(s,'contraception','Refere uso atual de contraceptivo','Nega uso atual de método contraceptivo','Não sabe informar o método contraceptivo');if(d.contraception==='Sim'){item(s,'method','Método');item(s,'methodTime','Tempo de uso');yn(s,'regularUse','Relata uso regular e correto do método','Relata uso irregular ou incorreto do método','Não sabe informar regularidade do uso');date(s,'lastDose','Última dose/aplicação');item(s,'methodNotes','Detalhes do uso');}item(s,'previousMethods','Métodos anteriores');yn(s,'unprotected','Refere relação sem proteção ou falha contraceptiva recente','Nega relação sem proteção ou falha contraceptiva recente','Não sabe informar sobre relação sem proteção ou falha recente');if(d.unprotected==='Sim')date(s,'unprotectedDate','Data da relação/falha mais recente');yn(s,'pregnancySymptoms','Refere atraso menstrual ou sintomas sugestivos de gestação','Nega atraso menstrual e sintomas sugestivos de gestação','Não sabe informar sobre sintomas de gestação');item(s,'pregnancyBasis','Fundamentação da avaliação de gestação');item(s,'pregnancyAssessment','Avaliação profissional quanto à possibilidade de gestação');item(s,'pregnancyTest','Teste de gravidez');if(['Negativo','Positivo','Inconclusivo'].includes(d.pregnancyTest)){date(s,'pregnancyTestDate','Data do teste de gravidez');item(s,'pregnancyTestType','Tipo/valor do teste');}push(s);
    const h=[];for(const [k,,label] of triage){if(d[k]==='Nega')h.push('Nega '+label);else if(d[k]==='Refere atual')h.push('Refere '+label+' atual');else if(d[k]==='Refere antecedente')h.push('Refere antecedente de '+label);else if(d[k]==='Não sabe informar')h.push('Não sabe informar sobre '+label);}item(h,'healthDetails','Detalhes dos antecedentes');item(h,'familyHistory','Histórico familiar');item(h,'otherConditions','Outras condições/alergias');yn(h,'meds','Refere uso de medicamentos/fitoterápicos','Nega uso de medicamentos/fitoterápicos','Não sabe informar medicamentos em uso');if(d.meds==='Sim')item(h,'medList','Medicamentos informados');item(h,'interactions','Revisão de interações');item(h,'interactionNotes','Observações sobre interações');push(h);
    const e=[];if(d.stiHistory==='Nega')e.push('Nega histórico de IST');else if(d.stiHistory==='Refere'){e.push('Refere histórico de IST');item(e,'stiDetails','Detalhes/seguimento de IST')}else if(d.stiHistory==='Não sabe informar')e.push('Não sabe informar histórico de IST');date(e,'cytologyDate','Último citopatológico');item(e,'cytologyStatus','Situação do citopatológico');item(e,'cytologyResult','Resultado/seguimento do citopatológico');for(const [k,label] of tests){if(v(d,k)||v(d,k+'Date'))e.push('Teste rápido para '+label+': '+(v(d,k)||'resultado não informado')+(v(d,k+'Date')?' (data: '+fmt(d[k+'Date'])+')':''))}item(e,'testNotes','Observações e condutas relativas aos testes');if(v(d,'pa'))e.push('PA: '+d.pa+' mmHg');if(v(d,'weight'))e.push('Peso: '+d.weight+' kg');item(e,'physical','Exame físico');push(e);
    const c=[];const gs=choices(d,'implantGuides').filter(k=>guides[k]).map(k=>guides[k]);if(gs.length)c.push('Realizadas orientações sobre '+gs.join('; '));item(c,'decision','Decisão da paciente');item(c,'understanding','Compreensão');item(c,'questions','Dúvidas e orientações adicionais');choices(d,'implantActions').filter(k=>actions[k]).forEach(k=>c.push(actions[k]));item(c,'assessment','Avaliação e justificativa da conduta');item(c,'consent','Termo de consentimento');item(c,'scoreStatus','Avaliação de vulnerabilidade');if(d.scoreStatus==='Realizado conforme protocolo local'){item(c,'scoreProtocol','Instrumento/protocolo');item(c,'scoreValue','Pontuação transcrita');item(c,'scoreNotes','Resultado e necessidades de apoio');}item(c,'requestStatus','Situação da solicitação');item(c,'reference','Protocolo/serviço de referência');item(c,'bridgePlan','Plano contraceptivo até avaliação/inserção');if(d.renewal==='Avaliação médica solicitada; aguardando definição')c.push('Solicitada avaliação médica para renovação de medicamentos; aguardando definição');else if(d.renewal==='Avaliação médica solicitada e realizada; renovação conforme orientação médica')c.push('Solicitada e realizada avaliação médica; medicamentos renovados conforme orientação médica'+(v(d,'renewedMeds')?': '+v(d,'renewedMeds'):''));else if(d.renewal==='Não')c.push('Não houve renovação de medicamentos neste atendimento');item(c,'conduct','Outras condutas');date(c,'returnDate','Retorno/agendamento');item(c,'returnPlace','Finalidade/local/horário do retorno');push(c);
    const end=[];item(end,'contact','Contato informado pela paciente');item(end,'contactPreference','Preferência segura de contato');item(end,'professional','Profissional responsável');push(end);
    if(!Object.entries(d).some(([k,x])=>!['output','stale'].includes(k)&&(Array.isArray(x)?x.length:String(x??'').trim())))throw Error('Preencha ao menos uma informação do atendimento.');
    return groups.join('\n\n');
  }
  return {form,mount,compose,validate};
})();
