const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const {JSDOM}=require('jsdom');
function setup(t){const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{url:'https://example.test',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(v){this.returnValue=v;this.dispatchEvent(new w.Event('close'))};const run=s=>vm.runInContext(s,dom.getInternalVMContext());for(const f of ['care.js','workflow.js','notes.js','prenatal.js','implante.js','diu.js','lab-details.js','shortcuts.js','renewal.js','app.js'])run(fs.readFileSync(f,'utf8'));t.after(()=>w.close());run("logged=true;page='occupational';render()");const set=(k,v)=>{const e=w.document.querySelector(`[name="${k}"]`);assert.ok(e,k);e.value=v;e.dispatchEvent(new w.Event('change',{bubbles:true}));};return{w,run,set};}
test('TO real-time composition, SOAP and manual edit protection',t=>{const {run,set,w}=setup(t);assert.equal(run('compose(Flow.data(),page)'), '');set('otDemand','organizar material escolar');run('LiveReview.update()');assert.match(w.document.querySelector('#output').value,/organizar material escolar/);set('otFormat','SOAP');run('LiveReview.update()');assert.match(w.document.querySelector('#output').value,/S:/);const out=w.document.querySelector('#output');out.value='Texto profissional preservado';out.dispatchEvent(new w.Event('input',{bubbles:true}));set('otReport','relato novo');run('LiveReview.update()');assert.equal(out.value,'Texto profissional preservado');});
test('Absence excludes session data and restores them when returning',t=>{const{run,set}=setup(t);set('otIntervention','atividade realizada');set('otMode','Ausência ou atendimento não realizado');set('otAbsentReason','não compareceu');let text=run('compose(Flow.data(),page)');assert.doesNotMatch(text,/atividade realizada/);assert.match(text,/não compareceu/);set('otMode','Acompanhamento');assert.match(run('compose(Flow.data(),page)'),/atividade realizada/);});
test('Multiple instruments and external source included without diagnosis',t=>{const{run,set,w}=setup(t);w.document.querySelector('#ot-add-test').click();set('otTest_1_name','M-CHAT-R/F');set('otTest_1_origin','Resultado externo apresentado');set('otTest_1_status','Completa');set('otTest_1_version','brasileira identificada');set('otTest_1_age','24');set('otTest_1_initial','5');assert.match(run('compose(Flow.data(),page)'),/Seguimento indicado/);assert.match(run('compose(Flow.data(),page)'),/Apresentado resultado/);w.document.querySelector('#ot-add-test').click();set('otTest_2_name','Katz');set('otTest_2_r1_value','4');assert.match(run('compose(Flow.data(),page)'),/Katz/);assert.equal(w.document.querySelectorAll('[name$="initial"]').length,2);});
test('MCHAT boundaries, missing, follow-up and age restrictions',t=>{const{run}=setup(t);const calc=r=>run(`Occupational.mchat(${JSON.stringify({age:'24',version:'documentada',status:'Completa',...r})})`);assert.equal(calc({}).text,'');for(const n of [0,2])assert.match(calc({initial:String(n)}).text,/baixa probabilidade/);for(const n of [3,7])assert.match(calc({initial:String(n)}).text,/não concluído/);for(const n of [8,20])assert.match(calc({initial:String(n)}).text,/positivo/);for(const n of [0,1])assert.match(calc({initial:'5',followState:'Concluída',follow:String(n)}).text,/negativo/);assert.match(calc({initial:'5',followState:'Concluída',follow:'2'}).text,/positivo/);assert.match(calc({initial:'5',followState:'Concluída',follow:''}).text,/não concluído/);assert.match(calc({initial:'5',age:'31'}).text,/indisponível/);assert.match(calc({initial:'5',age:''}).text,/indisponível/);assert.match(calc({initial:'5',status:'Parcial'}).text,/não concluída/);assert.equal(calc({initial:'21'}).errors.length,1);assert.equal(calc({initial:'5',follow:'6'}).errors.length,1);});
test('Conflicts are contextual and machine results do not replace professional analysis',t=>{const{run}=setup(t);assert.equal(run(`Occupational.issues({'c:otTask_1_help':['Sem ajuda de outra pessoa','Ajuda física total']}).length`),1);assert.equal(run(`Occupational.issues({'c:otTask_1_help':['Sem ajuda de outra pessoa','Recurso adaptado/tecnologia assistiva']}).length`),0);});
test('Follow-up invalidates on initial change and drafts restore rows',t=>{const{run,set,w}=setup(t);w.document.querySelector('#ot-add-test').click();set('otTest_1_name','M-CHAT-R/F');set('otTest_1_followState','Concluída');set('otTest_1_initial','5');assert.equal(w.document.querySelector('[name="otTest_1_followState"]').value,'Revisão necessária');set('otTest_1_informant','Familiar');run("navigate('general');navigate('occupational')");assert.equal(w.document.querySelector('[name="otTest_1_informant"]').value,'Familiar');});
test('Quantitative engine distinguishes omissions, zero scores and invalid answers',t=>{const{run}=setup(t);const spec={version:'ficticia-v1',permissionVerified:true,items:[{id:'a',options:[{value:'yes',points:0},{value:'no',points:1}]},{id:'b',options:[{value:'yes',points:1},{value:'no',points:0}]}]};const score=a=>run(`Occupational.scoreQuestionnaire(${JSON.stringify(spec)},${JSON.stringify(a)})`);assert.equal(score({a:'yes'}).score,null);assert.equal(score({a:'yes',b:'no'}).score,0);assert.equal(score({a:'no',b:'yes'}).score,2);assert.equal(score({a:'unknown',b:'no'}).state,'invalid');assert.equal(run('Occupational.scoreQuestionnaire({},{}).state'),'unavailable');});
